### ISSUE TITLE
Uncaught error when target element is blank .

### ISSUE THREAD

**Issue by KevinJump** [simonech/XliffLib#19]
If you import a XLIFF document with an empty target e.g.

```<target></target>```

Then the `.FromXliff` function fails as Target.Text is null or empty (so `Target.Text[0]` as PlainText).

_PR on it's way - just wanted issue number for branch_

**Comment by simonech** [comment]
Thank you.
The lib is still not feature complete, so I don't recommend using it for the moment.
But thx for mentioning and the PR.

**Comment by KevinJump** [comment]
it fine, i am in the middle of something that needed xliff, seemed odd to reinvent half of this stuff, given it's already there. If i add stuff i will throw it back over to see if its useful for you too.

**Comment by simonech** [comment]
@KevinJump thx...
